pyinstaller main_webapp_launcher.py ^
	--clean ^
	--onefile ^
	--noconfirm ^
	--name "Spaceships Generator" ^
	--icon assets\main_webapp\favicon.ico ^
	--add-data "./estimators;estimators" ^
	--add-data "./assets/main_webapp;assets" ^
	--add-data "./block_definitions.json;." ^
	--add-data "./common_atoms.json;." ^
	--add-data "./configs.ini;." ^
	--add-data "./hl_atoms.json;." ^
	--add-data "./hlrules;." ^
	--add-data "./llrules;." ^
	--add-data "./mapelites_human.json;." ^
	--add-data "./mapelites_random.json;." ^
	--add-data "./mapelites_greedy.json;." ^
	--add-data "./mapelites_contbandit.json;."
